# configure eureka client
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 3
#    prefer-ip-address: true
#    ip-address: 172.16.18.217
#  client:
#    serviceUrl:
#      defaultZone: http://172.16.18.217:8060/eureka
# configure Client Name
spring:
  application:
    name: mongolian-ecommerce-production
  # Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: bat
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
